development:
  mail_message_title: Notify from monitor
  mail_send_from: outpost@example.com
test:
  mail_message_title: Notify from monitor
  mail_send_from: test-receiver@gmail.com
production:
  mail_message_title: Notify from monitor
  mail_send_from: outpost@example.com